(* lua_bind_gen — generate LuaJIT FFI + OCaml externals + C stubs from a C header
   Usage: ocaml tools/lua_bind_gen.ml <header.h> [--prefix PREFIX] *)

let prefix = ref ""
let specs = ref []
let remaining_args = ref []

let () =
  Arg.parse
    [ "--prefix", Arg.Set_string prefix, " Function name prefix to strip (e.g. RLAPI_)" ]
    (fun s -> remaining_args := s :: !remaining_args)
    "lua_bind_gen [--prefix PREFIX] <header.h>";

  let args = List.rev !remaining_args in
  if List.length args < 1 then
    (Printf.eprintf "Usage: lua_bind_gen [--prefix PREFIX] <header.h>\n"; exit 1);

  let header = List.hd args in
  let base = Filename.chop_extension (Filename.basename header) in

  (* Read header *)
  let ic = open_in header in
  let lines = ref [] in
  (try while true do lines := input_line ic :: !lines done with End_of_file -> ());
  close_in ic;
  let content = String.concat "\n" (List.rev !lines) in

  (* Parse function declarations with regex *)
  let re = Str.regexp
    {|[A-Za-z_][A-Za-z0-9_]*[ \t]+[A-Za-z_][A-Za-z0-9_]*[ \t]*\([^)]*\)[ \t]*;|} in

  let decls = ref [] in
  let pos = ref 0 in
  (try
     while true do
       let start = Str.search_forward re content !pos in
       let m = Str.matched_string content in
       let len = String.length m in
       pos := start + len;
       (* Strip trailing semicolon *)
       let m = String.sub m 0 (len - 2) in
       (* Split into return type, name, and params *)
       let parts = Str.split (Str.regexp "[ \t]+") m in
       let parts = List.filter (fun s -> s <> "") parts in
       match parts with
       | ret :: name :: rest ->
           let params_str = String.concat " " rest in
           let params_str = String.sub params_str 1 (String.length params_str - 2) in
           (* Strip prefix *)
           let name = if !prefix <> "" && String.starts_with ~prefix:!prefix name
             then String.sub name (String.length !prefix) (String.length name - String.length !prefix)
             else name in
           decls := (ret, name, params_str) :: !decls
       | _ -> ()
     done
   with Not_found -> ());

  let decls = List.rev !decls in
  Printf.eprintf "Parsed %d function declarations\n" (List.length decls);

  (* Map C type to OCaml type *)
  let ocaml_type = function
    | "void" -> "unit"
    | "int" | "unsigned" | "unsigned int" -> "int"
    | "float" | "double" -> "float"
    | "bool" | "_Bool" -> "bool"
    | "char" -> "int"
    | s when String.length s > 2 && s.[String.length s - 1] = '*' -> "string"
    | s -> "int"  (* structs/unknown → opaque int *)
  in

  (* Strip pointer/array from param name *)
  let clean_param s =
    let s = Str.global_replace (Str.regexp "[*]+$") "" s in
    let s = Str.global_replace (Str.regexp "\\[.*\\]") "" s in
    s
  in

  let snake_name s =
    let b = Buffer.create (String.length s) in
    String.iter (fun c ->
        if c >= 'A' && c <= 'Z' then (Buffer.add_char b '_'; Buffer.add_char b (Char.lowercase_ascii c))
        else Buffer.add_char b c) s;
    let s = Buffer.contents b in
    if String.length s > 0 && s.[0] = '_' then String.sub s 1 (String.length s - 1) else s
  in

  let ocaml_params = Hashtbl.create 16 in
  let ocaml_results = Hashtbl.create 16 in
  let stubs_written = Hashtbl.create 16 in

  (* Generate OCaml external declarations *)
  let ocaml_file = base ^ "_external.ml" in
  let oc = open_out ocaml_file in
  Printf.fprintf oc "(* Auto-generated by lua_bind_gen from %s *)\n\n" (Filename.basename header);
  List.iter (fun (ret, name, params_str) ->
    try
      let params = if params_str = "void" || params_str = "" then []
        else List.filter (fun s -> s <> "") (Str.split (Str.regexp ",") params_str)
      in
      let params = List.map (fun p ->
          let p = String.trim p in
          let parts = List.rev (Str.split (Str.regexp "[ \t]+") p) in
          match parts with
          | param_name :: type_parts ->
              let ctype = String.concat " " (List.rev type_parts) in
              let param_name = clean_param param_name in
              (ocaml_type ctype, param_name)
          | _ -> ("int", "x")) params
      in
      let ocaml_params_list = List.map fst params in
      let ocaml_ret = ocaml_type ret in
      let lua_name = snake_name name in
      let ocaml_sig = String.concat " -> " (ocaml_params_list @ [ocaml_ret]) in
      Printf.fprintf oc "external %s : %s = \"%s\"\n" lua_name ocaml_sig lua_name;
      Hashtbl.add ocaml_params lua_name params;
      Hashtbl.add ocaml_results lua_name ocaml_ret
    with _ -> Printf.eprintf "SKIP %s\n" name);
  close_out oc;
  Printf.printf "Wrote %s\n" ocaml_file;

  (* Generate C stubs *)
  let c_file = base ^ "_stubs.c" in
  let c = open_out c_file in
  Printf.fprintf c "/* Auto-generated by lua_bind_gen from %s */\n" (Filename.basename header);
  Printf.fprintf c "#include <caml/mlvalues.h>\n";
  List.iter (fun (_ret, name, _params_str) ->
      let lua_name = snake_name name in
      let params = try Hashtbl.find ocaml_params lua_name with Not_found -> [] in
      Printf.fprintf c "CAMLprim value %s(" lua_name;
      for i = 1 to List.length params do
        Printf.fprintf c "value v%d%s" i (if i < List.length params then "," else "");
      done;
      Printf.fprintf c ") {";
      for i = 1 to List.length params do
        Printf.fprintf c "(void)v%d;" i;
      done;
      let ret = try Hashtbl.find ocaml_results lua_name with Not_found -> "unit" in
      (match ret with
       | "unit" -> Printf.fprintf c " return Val_unit;"
       | "int" -> Printf.fprintf c " return Val_int(0);"
       | "bool" -> Printf.fprintf c " return Val_bool(0);"
       | "float" -> Printf.fprintf c " return Val_unit;"
       | _ -> Printf.fprintf c " return Val_int(0);");
      Printf.fprintf c " }\n";
      Hashtbl.add stubs_written lua_name true);
  close_out c;
  Printf.printf "Wrote %s\n" c_file;

  (* Generate LuaJIT bindings *)
  let lua_file = base ^ "_bindings.lua" in
  let l = open_out lua_file in
  Printf.fprintf l "-- Auto-generated by lua_bind_gen from %s\n" (Filename.basename header);
  Printf.fprintf l "local ffi = require(\"ffi\")\n\n";
  Printf.fprintf l "ffi.cdef([[\n";

  (* Collect unique types for cdef *)
  List.iter (fun (ret, name, params_str) ->
      Printf.fprintf l "  %s %s(%s);\n" ret name params_str) decls;
  Printf.fprintf l "]])\n\n";
  Printf.fprintf l "local C = ffi.C\n\n";

  (* OCaml value conversion helpers *)
  Printf.fprintf l "-- Convert OCaml tagged int to Lua number\n";
  Printf.fprintf l "local function ocaml_int(v)\n";
  Printf.fprintf l "  if type(v) == \"number\" then return math.floor(v / 2) end\n";
  Printf.fprintf l "  return v or 0\n";
  Printf.fprintf l "end\n\n";

  Printf.fprintf l "-- Convert OCaml boxed float to Lua number\n";
  Printf.fprintf l "local function ocaml_float(v)\n";
  Printf.fprintf l "  if type(v) == \"table\" and v[1] == 253 then return v[2] or 0 end\n";
  Printf.fprintf l "  if type(v) == \"number\" then return v / 2 end\n";
  Printf.fprintf l "  return v or 0\n";
  Printf.fprintf l "end\n\n";

  Printf.fprintf l "-- Convert OCaml string to Lua string\n";
  Printf.fprintf l "local function ocaml_string(v) return v end\n\n";

  Printf.fprintf l "-- Wrapper functions callable from OCaml via external\n";

  List.iter (fun (_ret, name, _params_str) ->
      let lua_name = snake_name name in
      let params = try Hashtbl.find ocaml_params lua_name with Not_found -> [] in
      if List.length params = 0 then
        Printf.fprintf l "function %s() return C.%s() end\n" lua_name name
      else (
        Printf.fprintf l "function %s(" lua_name;
        for i = 1 to List.length params do
          Printf.fprintf l "a%d" i;
          if i < List.length params then Printf.fprintf l ", ";
        done;
        Printf.fprintf l ")\n";
        Printf.fprintf l "  return C.%s(" name;
        for i = 1 to List.length params do
          let ctype, _pname = List.nth params (i-1) in
          (match ctype with
           | "int" | "bool" -> Printf.fprintf l "ocaml_int(a%d)" i
           | "float" | "double" -> Printf.fprintf l "ocaml_float(a%d)" i
           | "string" -> Printf.fprintf l "ocaml_string(a%d)" i
           | _ -> Printf.fprintf l "a%d" i);
          if i < List.length params then Printf.fprintf l ", ";
        done;
        Printf.fprintf l ")\n";
        Printf.fprintf l "end\n");
      Printf.fprintf l "\n") decls;

  close_out l;
  Printf.printf "Wrote %s\n" lua_file
